#!/bin/bash
# Terminate already running bar instances
killall -q paperview

# Wait until the processes have been shut down
while pgrep -u $UID -x paperview >/dev/null; do sleep 1; done

# Launch bar1 and bar2
# polybar example &
~/paperview/paperview train/ 5