#!/bin/bash
if [ `xinput list-props "SynPS/2 Synaptics TouchPad" | grep "Device Enabled" | awk '{ print $4 }'` == 1 ]; then 

	xinput disable "SynPS/2 Synaptics TouchPad"
else
	xinput enable  "SynPS/2 Synaptics TouchPad"
fi
